{% set name = "seispy" %}

{% set version = "1.2.16" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-{{ name }}/python-{{ name }}-{{ version }}.tar.gz
  sha256: d9aefcad2a9a734a53138a4938dd9fe414ebfeef41a51ff76c554d93513e48d7

build:
  number: 0
  noarch: python
  entry_points:
    - gen_rayp_lib=seispy.psrayp:gen_rayp_lib
    - prf=seispy.scripts:prf
    - srf=seispy.scripts:srf
    - setpar=seispy.rf:setpar
    - rf2depth=seispy.rf2depth_makedata:rf2depth
    - plotrt=seispy.plotRT:main
    - plotr=seispy.plotR:main
    - updatecatalog=seispy.updatecatalog:main
    - ndk2dat=seispy.updatecatalog:ndk2dat
    - ccp_profile=seispy.scripts:ccp_profile
    - hk=seispy.hk:hk
    - pickrf=seispy.pickui:main
    - rfani=seispy.scripts:rfani
    - ccp3d=seispy.scripts:ccp3d
    - get_pierce_points=seispy.scripts:get_pierce_points
    - veltxt2mod=seispy.modcreator:veltxt2mod
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib >=3.2.0
    - numpy >=1.19.0
    - obspy >=1.3.0
    - pandas >=1.0.0
    - pyqt >=5.12.0
    - python >=3.6
    - scipy >=1.1.0
    - scikits-bootstrap >=1.0.0

test:
  imports:
    - seispy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/python-seispy/
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Python module of seismology and receiver functions
  doc_url: https://seispy.xumijian.me/
  dev_url: https://github.com/xumi1993/seispy

extra:
  recipe-maintainers:
    - xumi1993
